update to detect default branch automatically

diff --git a/git-rebase/git-rebase b/git-rebase/git-rebase
--- a/git-rebase/git-rebase
+++ b/git-rebase/git-rebase
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 # This is a little script that:
-# 1. syncs the upstream master with origin master
-# 2. and then rebases the current branch to upstream master using the merge strategy
+# 1. syncs the upstream default branch with origin default branch (master or main usually)
+# 2. and then rebases the current branch to upstream default master using the merge strategy
 #
 # Usage:
 # git-rebase
@@ -13,9 +13,14 @@ if [ -n "$(git status -s -uno)" ]; then
     exit 1
 fi
 
+repo_user_repo_name=$(git config --get remote.origin.url | sed 's|^.*//||; s/.*@//; s/[^:/]\+[:/]//; s/.git$//')
+cmd="curl -s https://api.github.com/repos/${repo_user_repo_name} | jq --raw-output .default_branch"
+default_branch=$(eval "$cmd") || exit 1
+echo -e "\n\n*** Discovered default branch: $default_branch"
+
 cur_branch=$(git branch | sed -n '/\* /s///p')
-if [ "$cur_branch" = "master" ]; then
-    echo "Error: this script expects you to be on the branch you need to rebase, but this is a 'master' branch"
+if [ "$cur_branch" = "$default_branch" ]; then
+    echo "Error: this script expects you to be on the branch you need to rebase, but this is a $default_branch branch"
     echo "Exiting"
     exit 1
 fi
@@ -26,9 +31,9 @@ fi
 if [ -n "$(git remote get-url upstream 2> /dev/null)" ]; then
     echo "detected a fork, merging upstream/master into origin/master first"
     git fetch upstream
-    git checkout master
-    git merge --no-edit upstream/master
-    git push --set-upstream origin master
+    git checkout $default_branch
+    git merge --no-edit upstream/$default_branch
+    git push --set-upstream origin $default_branch
     git checkout -
 else
     echo "detected non-forked repo, updating origin"
@@ -36,6 +41,6 @@ else
 fi
 
 git pull --rebase
-git merge origin/master
+git merge origin/$default_branch
 
 echo "Now resolve conflicts if any, followed by git commit and finally git push"
